config/routes.rb
Devisefull::Application.routes.draw do

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :projects
  resources :authentications

  get "talk/twitter"
  get "talk/facebook"
  
  root :to => "projects#index"
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  
  def provider_name
    if provider == 'open_id'
      "OpenID"
    else
      provider.titleize
    end
  end
  
  def get_twitter_token
    prepare_access_token_twitter(self.token, self.secret)
  end
  
  def get_facebook_token
    prepare_access_token_facebook(self.token, self.secret)
  end
  
  # prepare token for twitter oauth
  def prepare_access_token_twitter(oauth_token, oauth_token_secret)
      consumer = OAuth::Consumer.new(ENV['TW_KEY'], ENV['TW_SECRET'], { 
        :site => "http://api.twitter.com" 
        }
      )
      # now create the access token object from passed values
      token_hash = { :oauth_token => oauth_token, :oauth_token_secret => oauth_token_secret }
      access_token = OAuth::AccessToken.from_hash(consumer, token_hash )
      return access_token
  end
  
  # prepare token for facebook oauth
  def prepare_access_token_facebook(oauth_token, oauth_token_secret)
    require 'oauth2'

    client = OAuth2::Client.new(ENV['FB_KEY'], ENV['FB_SECRET'], :site => 'https://graph.facebook.com')

    # token api explorer 145634995501895|2.AQDBDSIwZiJe83u3.3600.1313006400.1-732449366|UKy7KgpIU0fSXfZ6yqj2kTTY31g

    access_token = OAuth2::AccessToken.new client, oauth_token
    return access_token
  end
  
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :description, :start_at
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications, :dependent => :destroy
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def apply_omniauth(omniauth)
    self.email = omniauth['user_info']['email'] if email.blank?
    authentications.build(
      :provider => omniauth['provider'], 
      :uid => omniauth['uid'],
      :token => omniauth['credentials']['token'],
      :secret => omniauth['credentials']['secret']    
    )
  end
  
  def password_required?
    (authentications.empty? || !password.blank?) && super
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentications = current_user.authentications if current_user
  end
  
  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end
    end
  end
  
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :authenticate_user!

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to @project, :notice => "Successfully created project."
    else
      render :action => 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project, :notice  => "Successfully updated project."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url, :notice => "Successfully destroyed project."
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    session[:omniauth] = nil unless @user.new_record?
  end
  
  private
  
  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end
end

app/controllers/talk_controller.rb
class TalkController < ApplicationController

  def twitter

      content = 'No Twitter authentications for you'
      auth = current_user.authentications.find(:first, :conditions => { :provider => 'twitter' })

      # get the rigth token
      if auth
        access_token = auth.get_twitter_token

        # use the access token as an agent to get my infos
        response = access_token.request(:get, "http://api.twitter.com/1/users/show.json?screen_name=bondix")
        content = response.body
      end
      
      render :text => content
  end


  def facebook
    
    content = 'No Facebook authentications for you'
    
    auth = current_user.authentications.find(:first, :conditions => { :provider => 'facebook' })

    if auth
      # get the rigth token
      access_token = auth.get_facebook_token

      # use the access token as an agent to get the home timeline
      content = access_token.get('/97070757020')
    end

    render :text => content
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/talk_helper.rb
module TalkHelper
end

app/views/authentications/index.html.erb
<% title "Sign In Options" %>

<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You have signed in with these services:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <%= image_tag "#{authentication.provider}_32.png", :size => "32x32" %>
          <div class="provider"><%= authentication.provider_name %></div>
          <div class="uid"><%= authentication.uid %></div>
          <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>

<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>
  Twitter
</a>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %>
  Facebook
</a>
<a href="/auth/google_apps" class="auth_provider">
  <%= image_tag "google_apps_64.png", :size => "64x64", :alt => "Google" %>
  Google
</a>
<a href="/auth/open_id" class="auth_provider">
  <%= image_tag "open_id_64.png", :size => "64x64", :alt => "OpenID" %>
  OpenID
</a>
<div class="clear"></div>

<% unless user_signed_in? %>
  <p>
    <strong>Don't use these services?</strong>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "sign in", new_user_session_path %> with a password.
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>.<br />
          Not you? <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign In", authentications_path %>
        <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :start_at %><br />
    <%= f.datetime_select :start_at %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/projects/edit.html.erb
<% title "Edit Project" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @project %> |
  <%= link_to "View All", projects_path %>
</p>

app/views/projects/index.html.erb
<% title "Projects" %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Start At</th>
  </tr>
  <% for project in @projects %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.description %></td>
      <td><%= project.start_at %></td>
      <td><%= link_to "Show", project %></td>
      <td><%= link_to "Edit", edit_project_path(project) %></td>
      <td><%= link_to "Destroy", project, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Project", new_project_path %></p>

app/views/projects/new.html.erb
<% title "New Project" %>

<%= render 'form' %>

<p><%= link_to "Back to List", projects_path %></p>

app/views/projects/show.html.erb
<% title "Project" %>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>
<p>
  <strong>Start At:</strong>
  <%= @project.start_at %>
</p>

<p>
  <%= link_to "Edit", edit_project_path(@project) %> |
  <%= link_to "Destroy", @project, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", projects_path %>
</p>

app/views/talk/facebook.html.erb
<h1>Talk#facebook</h1>
<p>Find me in app/views/talk/facebook.html.erb</p>

app/views/talk/twitter.html.erb
<h1>Talk#twitter</h1>
<p>Find me in app/views/talk/twitter.html.erb</p>